# Generated by Django 4.1.7 on 2023-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('datetime', models.DateField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'brand_mstr',
            },
        ),
        migrations.DeleteModel(
            name='brand_mstr',
        ),
    ]
